config/routes.rb
Rails.application.routes.draw do

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'

  resources :themes

  root 'main#index'

  resources :users
  resources :values
  resources :themes
  resources :images
  resources :sessions, only: [:new, :create, :destroy]

  namespace :api, defaults: { format: :json } do
    match 'next_image', to: 'api#next_image', via: :get
    match 'prev_image', to: 'api#prev_image', via: :get
    match 'save_value', to: 'api#save_value', via: :get
  end

  match 'index',    to: 'main#index',           via: 'get'
  match 'about',    to: 'main#about',           via: 'get'
  match 'help',     to: 'main#help',            via: 'get'
  match 'contacts', to: 'main#contacts',        via: 'get'

  match 'work', to: 'work#index',via: 'get'
  match 'choose_image', to: 'work#choose_image', via: :get
  match 'choose_theme', to: 'work#choose_theme', via: :get
  match 'display_theme', to: 'work#display_theme', via: :post, as: :js


  match 'results_list',     to: 'work#results_list', via: :get
  match 'save_value',       to: 'api/api#save_value',   via: :get


  match 'signup', to: 'users#new', via: 'get'
  match 'signin', to: 'sessions#new', via: 'get'
  match 'signout', to: 'sessions#destroy', via: 'delete'

  get 'main/index'

  #root 'work#index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_footer.html.haml
%footer.footer
  -#%p Experteese
    -#{style: " display:inline-block; font-size: 1em"}

    -#2016
  -#%small
  -#  The
  -#  %a{:href => "http://www.railstutorial.org/"} Ruby on Rails Tutorial
  -#  by
  -#  %a{:href => "http://www.michaelhartl.com/"} Michael Hartl

  %h3{style: "color: #c4f7ff; font-size: 1.3em; position: relative; left: 20%; margin-top: .55em;"}
    Logic Experteese
    %i.fa.fa-copyright.iconsMain{ style: " font-size: 1.3em; " }
    = Date.current.year


  .footer_menu
    %nav
      %ul
        %li= link_to t('.about'), about_path
        %li= link_to t('.contact'), contacts_path
        -#%li
        -#  %a{:href => "http://news.railstutorial.org/"} News

app/views/shared/_header.html.haml
-#%header.navbar.navbar-fixed-top.navbar-inverse
-#  = link_to "sample app", root_path, id: "logo"
-#  %nav
-#    %ul.nav.navbar-nav.navbar-right
-#      %li= link_to "Home",   root_path
-#      %li= link_to "Help",   help_path
-#      %li= link_to "Log in", '#'

%header.navbar.navbar-fixed-top.navbar-inverse
  .container.header
    = link_to t('.logo_title'), root_path, id: "logo"
    .rails_logo
      = link_to image_tag("rails.png", alt: "Rails logo")
      -#%img{:alt => "Rails logo", :src => 'assets/rails.png', :title => "Rails logo",:style => "width:15%; height:15%;" }

      %p.locale
        -#.ru_link
        = link_to image_tag("Russia.jpg", alt: "",  style: "width: 10%; height: 10%", title: "Русский" ), locale: :ru
        -#= link_to image_tag("Russia.jpg", alt: "",  style: "width: 8%; height: 8%; " )+" РУ", locale: :ru
        -#%p{style: "color: #c4f7ff"}" РУ"
        -#= link_to_unless I18n.locale == :ru, "Русский", locale: :ru
        -#%image_tag(style= "width: 8%; height: 8%" src= "assets/Russia.jpg")
        -#|
        = link_to image_tag("United_Kingdom.jpg", alt: "",  style: "width: 12%; height: 12%", title: "English"), locale: :en
        -#= link_to image_tag("United_Kingdom.jpg", alt: "",  style: "width: 9%; height: 9%")+" EN", locale: :en
        -#= link_to_unless I18n.locale == :en, "English", locale: :en
        %b
          = I18n.locale



    %nav
      %ul.nav.navbar-nav.pull-right
        %li= link_to t('.home'), root_path, id: "home"
        %li= link_to t('.help'), help_path
        - if signed_in?
          -#%li= link_to "Users", '#'
          %li.logged
            #{current_user.email}
          = gravatar_for current_user
          %li= link_to t('.profile'), current_user
          %li= link_to t('.sign_out'), signout_path, method: "delete"
        - else
          %li= link_to t('.sign_in'), signin_path


        -#%p.locale
        -#  = link_to_unless I18n.locale == :ru, "Русский", locale: :ru
        -#  |
        -#  = link_to_unless I18n.locale == :en, "English", locale: :en
        -#
        -#  %b
        -#    = I18n.locale


    -#.dropdown
    -#  %button.btn.btn-primary.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
    -#    Dropdown Example
    -#    %span.caret
    -#  %ul.dropdown-menu
    -#    %li
    -#      %a{:href => "#"} HTML
    -#    %li
    -#      %a{:href => "#"} CSS
    -#    %li
    -#      %a{:href => "#"} JavaScript
    -#